### ISSUE TITLE
RulesBasedSampler as a Sub-Sampler of the RulesBasedSampler

### ISSUE THREAD

**Issue by tdarwin** [honeycombio/refinery#1343]
**Describe the solution you'd like**
It would be really awesome to be able to use the RulesBasedSampler as a sub-sampler of a Rule in the parent RulesBasedSampler.  Something like this:

```yaml
Samplers:
    __default__:
        RulesBasedSampler:
               - Name: Dealing with Errors
                 Conditions:
                    - Field: error
                      Operator: exists
                 Sampler:
                    RulesBasedSampler:
                        - Name: Ignore Errors From X Service
                          Conditions:
                            - Field: service.name
                            - Operator: =
                            - Value: service-x
                          Drop: true
                        - Name: All the important errors
                          Sampler:
                            EMADynamicSampler:
                              GoalSampleRate: 3
                              FieldList:
                                  - exception.type
                                  - error.message
```

**Describe alternatives you've considered**

We could probably also do something similar by allowing rules to have layered conditions, where some can be scoped to span and some to the trace, and then also allowing for OR conditioning rather than the AND conditioning we do.

**Additional context**

Haven't heard this from customers really, but was an interesting thought I had that sprung from some questions I'd received.
