### ISSUE TITLE
multi-arch docker publish broke

### ISSUE THREAD

**Issue by robbkidd** [honeycombio/refinery#335]
With #328, the docker save/load/push misses the multi-arch stuff. It only manages to publish the architecture matching the CI environment.

* v1.5.0
  * [ko building _and_ publishing to Docker Hub](https://app.circleci.com/pipelines/github/honeycombio/refinery/835/workflows/00335408-100a-4a2e-bd20-34fb4d4cd482/jobs/2316)
  * [multi-arch image at Docker Hub](https://hub.docker.com/layers/honeycombio/refinery/v1.5.0/images/sha256-4b9442fd68fc71078ccff17f48fc471ecb130662bdf098bc29902fdb61c4c6f3?context=explore)
* v1.5.1
  *  [ko building and publishing locally](https://app.circleci.com/pipelines/github/honeycombio/refinery/891/workflows/aa678b60-0d86-48c0-ac5b-f3a183d52029/jobs/2471?invite=true#step-104-2)
  * [docker tagging the resulting image with honeycombio user](https://app.circleci.com/pipelines/github/honeycombio/refinery/891/workflows/aa678b60-0d86-48c0-ac5b-f3a183d52029/jobs/2471?invite=true#step-104-2) - suspect that it is here or in the next step that the awareness of multiple architectures is lost
  * [docker extracting an image from the local registry and saving it](https://app.circleci.com/pipelines/github/honeycombio/refinery/891/workflows/aa678b60-0d86-48c0-ac5b-f3a183d52029/jobs/2471?invite=true#step-104-2) 
  * [single-arch image at Docker Hub](https://hub.docker.com/layers/honeycombio/refinery/1.5.1/images/sha256-083a743a553d37994c02872a4945ef972986e67f6454bc0c3758c2f7d4e95756?context=explore)

### Potential solution:

We go back to using `ko publish` in both a `build_docker` job that publishes locally and a `publish_docker` job that builds again and publishes to GitHub. As much as I would like to build once and publish what was built, that doesn't seem the be the supported pattern for the tool usage. At least, it's not apparent from the documentation on using `ko` that I've read so far.

I suspect we can work with the existing `build-docker.sh`.
* Update it to default `KO_DOCKER_REPO` to `ko.local` but override from an environment variable.
* Make the CI jobs `build_docker` and `publish_docker` basically the same, but set `KO_DOCKER_REPO` to `honeycombio` for publish:

```yaml
  build_docker:
    docker:
      - image: cimg/go:1.16
    steps:
      - run: go install github.com/google/ko@latest
      - checkout
      - setup_remote_docker
      - run: 
          name: build images and publish locally
          command: ./build-docker.sh

  publish_docker:
    docker:
      - image: cimg/go:1.16
    steps:
      - run: go install github.com/google/ko@latest
      - checkout
      - setup_remote_docker
      - run: 
          name: build images and publish to Docker Hub
          environment:
            KO_DOCKER_REPO: honeycombio
          command: ./build-docker.sh
```
