### ISSUE TITLE
Cache capacity reduction too aggressive (10000x)

### ISSUE THREAD

**Issue by leonsp-ai** [honeycombio/refinery#339]
**Versions**

- Go:
- Refinery: 1.5.1

**Steps to reproduce**

1. Configure refinery:
   ```
    resources:
      limits:
        cpu: "1"
        memory: 8Gi
        
        # To size the cache, set MaxAlloc to 80% of the system’s RAM in bytes
        # and set CacheCapacity to the MaxAlloc value divided by 1000.
        CacheCapacity = 6871947
        MaxAlloc = 6871947672
   ```
2. Send a lot of traces through
3. Refinery reduces cache capacity by a factor of 10,000x:
   > time="2021-10-12T14:31:40Z" level=error msg="reducing cache size due to memory overage" alloc=6873706776 cache_size.new=6211 cache_size.previous=6871947
4. Also, `collect_cache_entries_count / collect_cache_capacity = 40,000%`

**Additional context**

This is showing up as an issue for us because we immediately start getting `collect_cache_buffer_overrun` on the pod that auto-reduced its cache capacity, but not on any of the other pods.

This is what Refinery [is doing](https://github.com/honeycombio/refinery/blob/63fd239b38c5ea3b1a10b053d5d3e999518d4127/collect/collect.go#L183):

```golang
	// Reduce cache size by a fixed 10%, successive overages will continue to shrink.
	// Base this on the total number of actual traces, which may be fewer than
	// the cache capacity.
	oldCap := existingCache.GetCacheSize()
	oldTraces := existingCache.GetAll()
	newCap := int(float64(len(oldTraces)) * 0.9)

	// Treat any MaxAlloc overage as an error. The configured cache capacity
	// should be reduced to avoid this condition.
	i.Logger.Error().
		WithField("cache_size.previous", oldCap).
		WithField("cache_size.new", newCap).
		WithField("alloc", mem.Alloc).
		Logf("reducing cache size due to memory overage")
```

1. Why is it reducing it to 90% of oldTraces rather than 90% of oldCap when the [performance tuning recommendation](https://docs.honeycomb.io/manage-data-volume/refinery/scale-and-troubleshoot/#sizing-the-cache) is as follows?
   > To size the cache, set MaxAlloc to 80% of the system’s RAM in bytes and set CacheCapacity to the MaxAlloc value divided by 1000.
2. Is `len(oldTraces)` an accurate count? It seems to be a very different number from the `collect_cache_entries_count` metric.
