### ISSUE TITLE
Live reload of rules breaks cluster and requires restart

### ISSUE THREAD

**Issue by jwilm** [honeycombio/refinery#380]
We are seeing our Refinery cluster grind to a halt after reloading our rules. I ran a test to collect some data that might be useful for this report. Around 1426 PDT, I deployed the updated rules. At 1433 PDT, I restarted the deployment. Here are some of the observed behaviors:

Upstream responses drops to near 0
![image](https://user-images.githubusercontent.com/4285147/150609716-85db483e-5b13-47e8-83cc-310c45fd9335.png)

Peer communications stop
![image](https://user-images.githubusercontent.com/4285147/150609793-690da2af-0390-4ca9-ae67-c61b56bacce4.png)

Goroutines climb indefinitely
![image](https://user-images.githubusercontent.com/4285147/150610111-907062bd-01f8-4cfc-ad18-244a00cefa10.png)

**Versions**

- Go: Whatever the 1.8.0 refinery image was built with
- Refinery: 1.8.0

**Steps to reproduce**

1. Use rules based config
2. Change the rules in any way whatsoever, even just a name change
3. Observe cluster breaking

**Additional context**

Here's the rules based config we are testing with

```yaml
    rules.yaml: |
      SampleRate: 1
      Sampler: DeterministicSampler
      production:
        Sampler: RulesBasedSampler
        rule:
        - SampleRate: 1
          condition:
          - field: name
            operator: =
            value: sidekiq.job
          - field: name
            operator: =
            value: notification delivery
          - field: notification.created_source
            operator: =
            value: dashboard
          name: Sidekiq jobs from Dashboard
        - SampleRate: 1
          condition:
          - field: service.name
            operator: =
            value: journeyx
         name: Journeyx Traces 100%
        - sampler:
            TotalThroughputSampler:
              AddSampleRateKeyToTrace: true
              AddSampleRateKeyToTraceField: meta.sampler.key
              ClearFrequencySec: 60
              FieldList:
              - http.route
              - http.status_code
              - http.method
              - exception.type
              - meta.sampler.taint
              GoalThroughputPerSec: 1
              UseTraceLength: false
```

I suspect the key parts of our rules are that the traces we are forcing to a deteministic sample rate of 100% represent a small part of our overall volume, and the TotalThroughputSampler handles most of our trace data.

I realized after doing this test to collect the data that we are a patch version off of latest, but it looks like the latest release doesn't address this issue. Please let me know if you'd like me to retest with the latest release. 

Thanks for your consideration!
