### ISSUE TITLE
Feature: allow testing whether traces have a root span

### ISSUE THREAD

**Issue by kentquirk** [honeycombio/refinery#610]
**Is your feature request related to a problem? Please describe.**

Traces without a root span can happen for a wide variety of reasons -- but some customers would prefer to treat such traces differently in their sampling -- possibly even drop them.

Refinery has enough information to do this, but right now, there is no way to express this desire in Refinery's query language. 

**Describe the solution you'd like**

The rules-based sampler should allow expressing this condition so that it can be combined with other rules.

One solution is that we could add an operator similar to `exists` -- call it `has-root-span`. It would ignore any `field` specifier, and the `value` would be evaluated as a boolean. It would be evaluated like other rules, would be invalid in `span` scope, and look something like this in practice:

```yaml
                - Name: drop incomplete traces from the buggy service
                  Drop: true
                  Conditions:
                    - Operator: has-root-span
                      Value: false
                    - Field: service.name
                      Operator: =
                      Value: buggy-service
```

**Describe alternatives you've considered**

There doesn't seem to be one if you want to do this.
