### ISSUE TITLE
Convert does not correctly convert MaxAlloc or APIKeys

### ISSUE THREAD

**Issue by TylerHelmuth** [honeycombio/refinery#765]
**Versions**

- Refinery: 2.0.0

**Steps to reproduce**

Input:

```
config:
  APIKeys: 
    - test-key
  InMemCollector:
    MaxAlloc: 3865470566
```

Command: `convert helm -i test.yaml -o result.yaml`

output:

```
config:
    AccessKeys:
        AcceptOnlyListedKeys: true
    General:
        ConfigurationVersion: 2
        MinRefineryVersion: v2.0
```

expected output:

```
config:
    AccessKeys:
        AcceptOnlyListedKeys: true
        ReceiveKeys:
            - test-key
    Collection:
        MaxAlloc: 3.865GB
    General:
        ConfigurationVersion: 2
        MinRefineryVersion: v2.0
```

**Additional context**
