### ISSUE TITLE
Convert does not correctly handle converting `EMADynamicSamplerConfig.AdjustmentInterval`

### ISSUE THREAD

**Issue by TylerHelmuth** [honeycombio/refinery#766]
**Versions**

- Refinery: 2.0.0

**Steps to reproduce**

input:

```
rules:
  Sampler: DeterministicSampler
  SampleRate: 1
  test: # E&S kibble rules (hence lowercase)
    Sampler: RulesBasedSampler
    rule:
      - name: test
        condition:
          - field: service.name
            operator: =
            value: test
        sampler:
          EMADynamicSampler:
            Sampler: EMADynamicSampler
            AdjustmentInterval: 60
      - name: default rule
        SampleRate: 1
```

expected output:

```
rules:
    RulesVersion: 2
    Samplers:
        __default__:
            DeterministicSampler:
                SampleRate: 1
        test:
            RulesBasedSampler:
                Rules:
                    - Name: test
                      Conditions:
                        - Field: service.name
                          Operator: =
                          Value: test
                      Sampler:
                        EMADynamicSampler:
                            AdjustmentInterval: 1m0s
                    - Name: default rule
                      SampleRate: 1
```

actual output:

```
panic: readV1RulesIntoV2Sampler unable to unmarshal config: json: cannot unmarshal number into Go struct field EMADynamicSamplerConfig.rule.sampler.emadynamicsampler.adjustmentinterval of type config.Duration

goroutine 1 [running]:
main.convertRulesToNewConfig(0x105213f20?)
        /Users/tylerhelmuth/projects/honeycomb/refinery/tools/convert/ruleconvert.go:165 +0x25c
main.ConvertHelm(0x1400000e348, {0x1052503c8?, 0x14000010060})
        /Users/tylerhelmuth/projects/honeycomb/refinery/tools/convert/main.go:346 +0x55c
main.main()
        /Users/tylerhelmuth/projects/honeycomb/refinery/tools/convert/main.go:216 +0x93c

Process finished with the exit code 2
```

**Additional context**

It appears the the rules convert logic doesn't handle the situation where the old value was an int and the new value is a duration.
