### ISSUE TITLE
Convert cannot handle yaml conditions for improperly configured RulesBasedSampler

### ISSUE THREAD

**Issue by TylerHelmuth** [honeycombio/refinery#767]
**Versions**

- Refinery: 2.0.0

**Steps to reproduce**

Input

```
rules:
  Sampler: DeterministicSampler
  SampleRate: 1
  test: # E&S kibble rules (hence lowercase)
    Sampler: RulesBasedSampler
    rule:
      - name: test
        condition:
          field: service.name
          operator: =
          value: test
```

expected output:

```
rules:
    RulesVersion: 2
    Samplers:
        __default__:
            DeterministicSampler:
                SampleRate: 1
        test:
            RulesBasedSampler:
                Rules:
                    - Name: test
                      Conditions:
                        - Field: service.name
                          Operator: =
                          Value: test
```

actual output:

```
panic: readV1RulesIntoV2Sampler unable to unmarshal config: json: cannot unmarshal object into Go struct field RulesBasedSamplerRule.rule.condition of type []*config.RulesBasedSamplerCondition

goroutine 1 [running]:
main.convertRulesToNewConfig(0x102837f20?)
        /Users/tylerhelmuth/projects/honeycomb/refinery/tools/convert/ruleconvert.go:165 +0x25c
main.ConvertHelm(0x1400000e2e8, {0x1028743c8?, 0x14000010060})
        /Users/tylerhelmuth/projects/honeycomb/refinery/tools/convert/main.go:346 +0x55c
main.main()
        /Users/tylerhelmuth/projects/honeycomb/refinery/tools/convert/main.go:216 +0x93c

Process finished with the exit code 2
```

**Additional context**

It seems the issue is because the old Refinery could handle converting from 

```
Conditions:
  Field: service.name
  Operator: =
  Value: test
```

to a list of conditions even tho that is not how a list is defined in refinery.  When converting helm the convert tool expects proper yaml so when it sees the above configuration it cannot unmarshal it as expected.

As a workaround 

```
Conditions:
  - Field: service.name
    Operator: =
    Value: test
```

is converted correctly.
