### ISSUE TITLE
HoneycombLogger requires APIKey when dataset is set, even if APIKey is being supplied by an env var

### ISSUE THREAD

**Issue by TylerHelmuth** [honeycombio/refinery#775]
**Versions**

- Refinery: 2.0.0

**Steps to reproduce**

A config like the one below will fail even if `REFINERY_HONEYCOMB_API_KEY` is being used.

```
HoneycombLogger:
        Dataset: refinery-logs
    LegacyMetrics:
        Dataset: refinery-metrics
```

**Additional context**

It appears the that validate logic is too strict; it doesn't take into account the fact that the APIKey's value could be coming from an env variable.
