### ISSUE TITLE
Structured: true does not generate json logs

### ISSUE THREAD

**Issue by KaoruDev** [honeycombio/refinery#842]
Settings `Structured: true` does not generate JSON logs. I see the following:

```
time="2023-08-19T21:55:27Z" level=info msg="Sending trace" environment=dev reason=deterministic/always trace_id=9f15b4d3a2148cc63455e1d7fa638bb3
time="2023-08-19T21:55:51Z" level=info msg="Sending trace" environment=dev reason=deterministic/always trace_id=0362fb07db9239527ec430e8d6962098
time="2023-08-19T21:55:53Z" level=info msg="Sending trace" environment=dev reason=deterministic/always trace_id=31f573d8fcbbd81ce3847a4e14fbf812
time="2023-08-19T21:55:53Z" level=info msg="Sending trace" environment=dev reason=deterministic/always trace_id=2e737f6f82c154ba8f81f522eabd43da
time="2023-08-19T21:55:53Z" level=info msg="Sending trace" environment=dev reason=deterministic/always trace_id=2bd74614c0ba61e980c59eb517668360
```

**Versions**

Docker image: `honeycombio/refinery:2.1.0`

**Steps to reproduce**

1. Set the following config:
```yaml
Debugging:
  AdditionalErrorFields:
    - trace.span_id
    - name
  DryRun: false
Logger:
  Type: "stdout"
  Level: info
StdoutLogger:
  Structured: false
```

**Additional context**
