### ISSUE TITLE
Logger does not send logs to stdout even tho Logger.Type = stdout

### ISSUE THREAD

**Issue by KaoruDev** [honeycombio/refinery#843]
Refinery still writes to `stderr` even tho `Logger.Type: stdout`. Below is a screenshot of the logs captured via GCP's Cloud Logging:

<img width="1673" alt="Logs_Explorer_–_Logging_–_US_Family_Dev_–_Google_Cloud_console" src="https://github.com/honeycombio/refinery/assets/5273755/84bb74ee-f5f4-4746-8566-6dc631fdb6af">

This is problematic because logs that are not errors show up as errors because they're being written to `stderr`

**Versions**

Docker image: `honeycombio/refinery:2.1.0`

**Steps to reproduce**

1. Set the following config:
```yaml
Debugging:
  AdditionalErrorFields:
    - trace.span_id
    - name
  DryRun: false
Logger:
  Type: "stdout"
  Level: info
StdoutLogger:
  Structured: false
```

**Additional context**
